---
markdown: kramdown
highlighter: rouge
title: Franck Picard
tagline: A Jekyll theme
url: https://franckpicard.github.io
baseurl: ""

author:
  name: Franck Picard
#  url: https://twitter.com/fongandrewc
paginate: 5

exclude:
- README.md

plugins:
- jekyll-feed
- jekyll-gist
- jekyll-paginate
- jekyll/scholar
- jemoji

sidebar_home_link: true

# Jekyll-Scholar
scholar:

  last_name: Picard

  style: assets/bib/jc-style.csl
  #style: /home/picard/website/assets/bib/jc-style.csl
  locale: en

  sort_by: year
  order: descending

  source: _bibliography/
  #source: /home/picard/website/_bibliography/
  bibliography: papers.bib
  bibliography_template: <div class="text-justify">{{reference}}</div>

fonts:

 primary: Roboto Slab
 secondary: Helvetica

theme_colors:
  sidebar-bg-color: "#000000"
  sidebar-fg-color: "#FFFFFF"
  link-color: "#000000"

sidebar-sticky: true

layout-reverse: false

remote_theme: fongandrew/hydeout

google_analytics: ''
disqus:
  shortname: ''
theme: jekyll-theme-hydeout
