---
markdown: kramdown
highlighter: rouge
title: Franck Picard
url: https://franckpicard.github.io
baseurl: '' # /franckpicard.github.io

author:
  name: Franck Picard
#  url: https://twitter.com/fongandrewc
paginate: 5

exclude:
- README.md

plugins:
- jekyll-feed
- jekyll-gist
- jekyll-paginate
- jekyll/scholar
- jemoji

sidebar_home_link: true


font:         Noto Sans, Helvetica, Arial, sans-serif
font_heading: Roboto Slab, Helvetica, Arial, sans-serif
google_fonts: Roboto+Slab:700|Noto+Sans:400,400i,700,700i

theme_colors:
  sidebar-bg-color: "#0B1728" 
  sidebar-fg-color: "#FFFFFF"
  link-color: "#268bd2"

sidebar-sticky: true

layout-reverse: false

remote_theme: fongandrew/hydeout

google_analytics: ''
disqus:
  shortname: ''
theme: jekyll-theme-hydeout
