---
markdown: kramdown
highlighter: rouge
title: Hydeout
tagline: A Jekyll theme
description: Franck Picard homepage
url: https://franckpicard.github.io
baseurl: ""

author:
  name: Franck Picard
#  url: https://twitter.com/fongandrewc
paginate: 5

exclude:
- README.md

plugins:
- jekyll-feed
- jekyll-gist
- jekyll-paginate

sidebar_home_link: true

fonts:

 primary: Roboto Slab
 secondary: Helvetica

theme_colors:
  sidebar-bg-color: "#000000"
  sidebar-fg-color: "#FFFFFF"
  link-color: "#000000"

sidebar-sticky: true

layout-reverse: false

remote_theme: fongandrew/hydeout

google_analytics: ''
disqus:
  shortname: ''
theme: jekyll-theme-hydeout
